// <auto-generated />
using System;
using CleanArchitecture.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic gadgets and devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Various kinds of books",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apparel and accessories",
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 21, 16, 2, 34, 931, DateTimeKind.Local).AddTicks(7544),
                            Email = "JohnDeo@example.com",
                            IsDeleted = false,
                            Name = "John Doe",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 21, 16, 2, 34, 932, DateTimeKind.Local).AddTicks(4558),
                            Email = "JaneSmith@example.com",
                            IsDeleted = false,
                            Name = "Jane Smith",
                            PhoneNumber = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 21, 16, 2, 34, 932, DateTimeKind.Local).AddTicks(4568),
                            Email = "Alice@mailer.com",
                            IsDeleted = false,
                            Name = "Alice Johnson",
                            PhoneNumber = "555-123-4567"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 21, 16, 2, 34, 932, DateTimeKind.Local).AddTicks(4570),
                            Email = "SpownBob@cc.com",
                            IsDeleted = false,
                            Name = "Bob Brown",
                            PhoneNumber = "444-555-6666"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderCode = "",
                            OrderDate = new DateTime(2026, 1, 11, 16, 2, 34, 932, DateTimeKind.Local).AddTicks(5234),
                            TotalAmount = 899.98m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderCode = "",
                            OrderDate = new DateTime(2026, 1, 16, 16, 2, 34, 932, DateTimeKind.Local).AddTicks(5562),
                            TotalAmount = 199.99m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderCode = "",
                            OrderDate = new DateTime(2026, 1, 19, 16, 2, 34, 932, DateTimeKind.Local).AddTicks(5565),
                            TotalAmount = 1299.99m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            OrderCode = "",
                            OrderDate = new DateTime(2026, 1, 20, 16, 2, 34, 932, DateTimeKind.Local).AddTicks(5567),
                            TotalAmount = 699.99m
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 699.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 199.99m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 199.99m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 1299.99m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 4,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 699.99m
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest model smartphone",
                            IsDeleted = false,
                            Name = "Smartphone",
                            Price = 699.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "High performance laptop",
                            IsDeleted = false,
                            Name = "Laptop",
                            Price = 1299.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Bestselling fiction mouse",
                            IsDeleted = false,
                            Name = "Mouse",
                            Price = 19.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "High quality and high light power",
                            IsDeleted = false,
                            Name = "Display Screen",
                            Price = 9.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Noise-cancelling headphones",
                            IsDeleted = false,
                            Name = "Headphones",
                            Price = 199.99m,
                            StockQuantity = 75
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Order", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Product", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
